### ISSUE TITLE
Implement end-to-end API test for DACs

### ISSUE THREAD

**Issue by sohkai** [bigchaindb/coalaip-api#14]
The (integration) test should traverse the following sequence:

![Alt text](http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    api [shape=box];
    api -> pycoalaip;
    api [label="COALA IP API -- Register Operation"]
    pycoalaip -> "bigchaindb-coalaip";
    "bigchaindb-coalaip" ->  "bigchaindb-driver";
    subgraph cluster_bdb {
        "bigchaindb-driver" -> ipdb;
        ipdb [label="IPDB/BigchainDB"
        graph[style=dotted];
    }
  }
)

# Phases

## Phase I
- [x] `COALA IP API` needs its repository, and perhaps renaming
- [x] `pycoalaip` needs its repository, and perhaps renaming
- [x] `bigchaindb-coalaip` needs its repository, and perhaps renaming
- [x] Choose licenses with @gmcmullen help :smile: 

## Phase II
- [x] `COALA IP API`: flask or django -- choose
- [x] `pycoalaip` packaging boilerplate to be able to pip install it -- just register on PyPI
- [x] `bigchaindb-coalaip` packaging boilerplate to be able to pip install it - just register on PyPI
- [ ] `bigchaindb-driver` is usable/callable for a basic TX

## Phase III
- [x] `COALA IP API`: create project boilerplate -- (issue #30)

## Phase IV
- [ ] `COALA IP API`: implement first API call: `REGISTER` in conjunction with the test
- [ ] `pycoalaip` implement `REGISTER` -- upload on PyPI
- [ ] `bigchaindb-coalaip` supports the above operation (`REGISTER`), in an abstract/generic way -- upload on PyPI

# Notes
The API test assumes that the underlying dependencies (direct and indirect) work as expected. In other words, `pycoalaip` is assumed to work as expected, just so as the others (`bigchaindb-coalaip`, `bigchaindb-driver`).

## Testing infrastructure
`docker` and `docker-compose` can be used to run a `bigchaindb` node.

**Comment by sohkai** [comment]
Closing for https://github.com/bigchaindb/pycoalaip/issues/4 after project scope changes.
